#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${1:-$root/examples/llmwave-big-broad-public-corpus-100k.txt}"
manifest="${2:-$root/examples/llmwave-big-broad-public-corpus-100k.manifest.json}"

mkdir -p "$(dirname "$out")"

domains=(
  "code"
  "contracts"
  "business"
  "customs"
  "runtime"
  "finance"
  "dialogue"
  "adversarial"
  "research"
  "release"
)

routes=(
  "owner_route"
  "adapter_boundary"
  "cli_dispatch"
  "test_contract"
  "protocol_direction"
  "payment_obligation"
  "penalty_clause"
  "edo_effect"
  "supplier_docs"
  "buyer_supplier_roles"
  "invoice_shipment"
  "manufacturer_address"
  "declaration_route"
  "certification_route"
  "border_docs"
  "hs_code_route"
  "symptom_action"
  "runtime_state"
  "config_ui_mismatch"
  "stale_build"
  "rate_fact"
  "source_timestamp"
  "payer_beneficiary"
  "product_boundary"
  "accepted_correction"
  "rejected_answer"
  "route_memory_update"
  "followup_uses_correction"
  "same_name_different_route"
  "old_fact_vs_current_fact"
  "lexical_match_wrong_role"
  "route_splice"
  "literature_anchor"
  "hrr_binding"
  "oscillatory_field"
  "dense_associative_memory"
  "release_gate"
  "version_contract"
  "public_private_split"
  "claim_boundary"
  "evidence_binding"
  "negative_shortcut"
  "focus_window"
  "heldout_leakage"
  "route_balance"
  "hub_dominance"
  "duplicate_pressure"
  "answer_grounding"
  "feedback_learning"
  "anti_wave_safety"
)

relations=(
  "requires"
  "supports"
  "must_not_merge"
  "does_not_prove"
  "routes_to"
  "updates"
  "suppresses"
  "binds_to"
  "overrides"
  "must_delegate_to"
)

objects=(
  "owner evidence"
  "route proof"
  "held-out guard"
  "focus packet"
  "negative shortcut"
  "claim boundary"
  "source timestamp"
  "role binding"
  "field coherence"
  "answer grounding"
)

{
  echo "# Public-safe LLMWave broad corpus 100k."
  echo "# Generated by scripts/build-llmwave-big-broad-public-corpus.sh."
  echo "# Format: domain|route|subject|relation|object|evidence"
  echo "# Private user/business/local correspondence data is intentionally excluded."
  for domain_idx in "${!domains[@]}"; do
    domain="${domains[$domain_idx]}"
    for route_idx in "${!routes[@]}"; do
      route="${routes[$route_idx]}"
      for item_idx in $(seq 0 199); do
        global_id=$((domain_idx * ${#routes[@]} * 200 + route_idx * 200 + item_idx + 1))
        rel="${relations[$(((route_idx + item_idx) % ${#relations[@]}))]}"
        obj="${objects[$(((domain_idx + route_idx + item_idx) % ${#objects[@]}))]}"
        subject="${domain}.${route}.subject.$(printf '%06d' "$item_idx")"
        object="${domain}.${route}.${obj}.$(printf '%06d' "$global_id")"
        evidence="public-safe generated route fact $(printf '%06d' "$global_id"); no private user data; domain=$domain; route=$route"
        printf '%s|%s|%s|%s|%s|%s\n' "$domain" "$route" "$subject" "$rel" "$object" "$evidence"
      done
    done
  done
} > "$out"

cat > "$manifest" <<JSON
{
  "artifact": "llmwave-big-broad-public-corpus-100k",
  "version": "1",
  "generator": "scripts/build-llmwave-big-broad-public-corpus.sh",
  "corpus_path": "examples/llmwave-big-broad-public-corpus-100k.txt",
  "fact_count": 100000,
  "domain_count": ${#domains[@]},
  "route_count": ${#routes[@]},
  "facts_per_domain_route": 200,
  "privacy_policy": {
    "private_user_data_excluded": true,
    "allowed_sources": [
      "public-safe generated structural facts",
      "generic route templates",
      "repository-public documentation concepts"
    ],
    "excluded_sources": [
      "user correspondence",
      "customs folders",
      "contract originals",
      "commercial documents",
      "customer or counterparty data",
      "browser/session exports",
      "private project notes outside this repository"
    ]
  },
  "claim_boundary": {
    "proves_big_broad_artifact_exists": true,
    "proves_llm_ready": false,
    "proves_nonlinear_memory": false,
    "safe_claim": "This is a public-safe 100k structural corpus for broad eval pipeline development, not proof of general LLM readiness."
  }
}
JSON

wc -l -c "$out"
