#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${1:-$root/examples/llmwave-big-broad-public-corpus-100k.txt}"
manifest="${2:-$root/examples/llmwave-big-broad-public-corpus-100k.manifest.json}"
fact_count="${3:-100000}"

mkdir -p "$(dirname "$out")"

if ! [[ "$fact_count" =~ ^[0-9]+$ ]] || [[ "$fact_count" -le 0 ]]; then
  echo "fact_count must be a positive integer" >&2
  exit 2
fi

domains=(
  "code"
  "contracts"
  "business"
  "customs"
  "runtime"
  "finance"
  "dialogue"
  "adversarial"
  "research"
  "release"
)

routes=(
  "owner_route"
  "adapter_boundary"
  "cli_dispatch"
  "test_contract"
  "protocol_direction"
  "payment_obligation"
  "penalty_clause"
  "edo_effect"
  "supplier_docs"
  "buyer_supplier_roles"
  "invoice_shipment"
  "manufacturer_address"
  "declaration_route"
  "certification_route"
  "border_docs"
  "hs_code_route"
  "symptom_action"
  "runtime_state"
  "config_ui_mismatch"
  "stale_build"
  "rate_fact"
  "source_timestamp"
  "payer_beneficiary"
  "product_boundary"
  "accepted_correction"
  "rejected_answer"
  "route_memory_update"
  "followup_uses_correction"
  "same_name_different_route"
  "old_fact_vs_current_fact"
  "lexical_match_wrong_role"
  "route_splice"
  "literature_anchor"
  "hrr_binding"
  "oscillatory_field"
  "dense_associative_memory"
  "release_gate"
  "version_contract"
  "public_private_split"
  "claim_boundary"
  "evidence_binding"
  "negative_shortcut"
  "focus_window"
  "heldout_leakage"
  "route_balance"
  "hub_dominance"
  "duplicate_pressure"
  "answer_grounding"
  "feedback_learning"
  "anti_wave_safety"
)

relations=(
  "requires"
  "supports"
  "must_not_merge"
  "does_not_prove"
  "routes_to"
  "updates"
  "suppresses"
  "binds_to"
  "overrides"
  "must_delegate_to"
)

objects=(
  "owner evidence"
  "route proof"
  "held-out guard"
  "focus packet"
  "negative shortcut"
  "claim boundary"
  "source timestamp"
  "role binding"
  "field coherence"
  "answer grounding"
)

domain_count="${#domains[@]}"
route_count="${#routes[@]}"
bucket_count=$((domain_count * route_count))
if (( fact_count % bucket_count != 0 )); then
  echo "fact_count must be divisible by $bucket_count for a balanced corpus" >&2
  exit 2
fi
facts_per_domain_route=$((fact_count / bucket_count))

domain_csv="$(IFS=,; echo "${domains[*]}")"
route_csv="$(IFS=,; echo "${routes[*]}")"
relation_csv="$(IFS=,; echo "${relations[*]}")"
object_csv="$(IFS=,; echo "${objects[*]}")"

awk \
  -v fact_count="$fact_count" \
  -v facts_per_domain_route="$facts_per_domain_route" \
  -v domains="$domain_csv" \
  -v routes="$route_csv" \
  -v relations="$relation_csv" \
  -v objects="$object_csv" '
BEGIN {
  nd = split(domains, d, ",")
  nr = split(routes, r, ",")
  nrel = split(relations, rels, ",")
  nobj = split(objects, objs, ",")
  print "# Public-safe LLMWave broad corpus " fact_count "."
  print "# Generated by scripts/build-llmwave-big-broad-public-corpus.sh."
  print "# Format: domain|route|subject|relation|object|evidence"
  print "# Private user/business/local correspondence data is intentionally excluded."
  global_id = 0
  for (di = 1; di <= nd; di++) {
    domain = d[di]
    for (ri = 1; ri <= nr; ri++) {
      route = r[ri]
      for (ii = 0; ii < facts_per_domain_route; ii++) {
        global_id++
        rel = rels[((ri - 1 + ii) % nrel) + 1]
        obj = objs[((di - 1 + ri - 1 + ii) % nobj) + 1]
        subject = sprintf("%s.%s.subject.%06d", domain, route, ii)
        object = sprintf("%s.%s.%s.%09d", domain, route, obj, global_id)
        evidence = sprintf("public-safe generated route fact %09d; no private user data; domain=%s; route=%s", global_id, domain, route)
        printf "%s|%s|%s|%s|%s|%s\n", domain, route, subject, rel, object, evidence
      }
    }
  }
}' > "$out"

cat > "$manifest" <<JSON
{
  "artifact": "llmwave-big-broad-public-corpus-${fact_count}",
  "version": "1",
  "generator": "scripts/build-llmwave-big-broad-public-corpus.sh",
  "corpus_path": "$out",
  "fact_count": $fact_count,
  "domain_count": $domain_count,
  "route_count": $route_count,
  "facts_per_domain_route": $facts_per_domain_route,
  "privacy_policy": {
    "private_user_data_excluded": true,
    "allowed_sources": [
      "public-safe generated structural facts",
      "generic route templates",
      "repository-public documentation concepts"
    ],
    "excluded_sources": [
      "user correspondence",
      "customs folders",
      "contract originals",
      "commercial documents",
      "customer or counterparty data",
      "browser/session exports",
      "private project notes outside this repository"
    ]
  },
  "claim_boundary": {
    "proves_big_broad_artifact_exists": true,
    "proves_llm_ready": false,
    "proves_nonlinear_memory": false,
    "safe_claim": "This is a public-safe structural corpus for broad eval pipeline development, not proof of general LLM readiness."
  }
}
JSON

wc -l -c "$out"
