#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
codex_home="${CODEX_HOME:-$HOME/.codex}"
skill_name="nanda-structural-gate"
runtime_skill_dir="$codex_home/skills/$skill_name"
bin_dir="$HOME/.local/bin"

mkdir -p "$codex_home/skills" "$bin_dir"
cargo build --release --manifest-path "$root/Cargo.toml"
rm -rf "$runtime_skill_dir"
cp -a "$root/$skill_name" "$runtime_skill_dir"
mkdir -p "$runtime_skill_dir/bin"
cp "$root/target/release/nanda" "$runtime_skill_dir/bin/nanda"
chmod +x "$runtime_skill_dir/scripts/nanda-check"
chmod +x "$runtime_skill_dir/scripts/nanda-gate"
chmod +x "$runtime_skill_dir/scripts/nanda-init-task"
chmod +x "$runtime_skill_dir/scripts/nanda-pack-from-md"
chmod +x "$runtime_skill_dir/scripts/nanda-init-md"
chmod +x "$runtime_skill_dir/scripts/nanda-gate-md"
chmod +x "$runtime_skill_dir/scripts/nanda-self-check"
chmod +x "$runtime_skill_dir/scripts/nanda-comb"
chmod +x "$runtime_skill_dir/scripts/nanda-doctor"
chmod +x "$runtime_skill_dir/scripts/nanda-extract"
chmod +x "$runtime_skill_dir/scripts/nanda-eval"
chmod +x "$runtime_skill_dir/scripts/nanda-waw"
chmod +x "$runtime_skill_dir/scripts/nanda-feedback"
chmod +x "$runtime_skill_dir/scripts/nanda-index"
chmod +x "$runtime_skill_dir/scripts/nanda-search"
chmod +x "$runtime_skill_dir/scripts/nanda-encode"
chmod +x "$runtime_skill_dir/scripts/nanda-decode"
chmod +x "$runtime_skill_dir/scripts/nanda-decode-eval"
chmod +x "$runtime_skill_dir/scripts/nanda-pattern-store"
chmod +x "$runtime_skill_dir/scripts/nanda-pattern-capacity"
chmod +x "$runtime_skill_dir/scripts/nanda-pattern-eval"
chmod +x "$runtime_skill_dir/scripts/nanda-llmwave"
chmod +x "$runtime_skill_dir/scripts/nanda-focus"
chmod +x "$runtime_skill_dir/scripts/nanda-proof"
chmod +x "$runtime_skill_dir/scripts/nanda-probe"
chmod +x "$runtime_skill_dir/scripts/nanda-dataset-doctor"
chmod +x "$runtime_skill_dir/scripts/nanda-aliases"
chmod +x "$runtime_skill_dir/scripts/nanda-budget"
chmod +x "$runtime_skill_dir/scripts/nanda-pack6m"
chmod +x "$runtime_skill_dir/scripts/nanda-bench6m"
chmod +x "$runtime_skill_dir/scripts/nanda-serve"
chmod +x "$runtime_skill_dir/scripts/nanda-dogfood"
chmod +x "$runtime_skill_dir/scripts/nanda-report"
chmod +x "$runtime_skill_dir/scripts/nanda-split"
chmod +x "$runtime_skill_dir/scripts/nanda-split-md"
chmod +x "$runtime_skill_dir/scripts/nanda-map"
chmod +x "$runtime_skill_dir/scripts/nanda-map-code"
chmod +x "$runtime_skill_dir/scripts/nanda-hgate"
ln -sfn "$runtime_skill_dir/bin/nanda" "$bin_dir/nanda"
ln -sfn "$runtime_skill_dir/scripts/nanda-check" "$bin_dir/nanda-check"
ln -sfn "$runtime_skill_dir/scripts/nanda-gate" "$bin_dir/nanda-gate"
ln -sfn "$runtime_skill_dir/scripts/nanda-init-task" "$bin_dir/nanda-init-task"
ln -sfn "$runtime_skill_dir/scripts/nanda-pack-from-md" "$bin_dir/nanda-pack-from-md"
ln -sfn "$runtime_skill_dir/scripts/nanda-init-md" "$bin_dir/nanda-init-md"
ln -sfn "$runtime_skill_dir/scripts/nanda-gate-md" "$bin_dir/nanda-gate-md"
ln -sfn "$runtime_skill_dir/scripts/nanda-self-check" "$bin_dir/nanda-self-check"
ln -sfn "$runtime_skill_dir/scripts/nanda-comb" "$bin_dir/nanda-comb"
ln -sfn "$runtime_skill_dir/scripts/nanda-doctor" "$bin_dir/nanda-doctor"
ln -sfn "$runtime_skill_dir/scripts/nanda-extract" "$bin_dir/nanda-extract"
ln -sfn "$runtime_skill_dir/scripts/nanda-eval" "$bin_dir/nanda-eval"
ln -sfn "$runtime_skill_dir/scripts/nanda-waw" "$bin_dir/nanda-waw"
ln -sfn "$runtime_skill_dir/scripts/nanda-feedback" "$bin_dir/nanda-feedback"
ln -sfn "$runtime_skill_dir/scripts/nanda-index" "$bin_dir/nanda-index"
ln -sfn "$runtime_skill_dir/scripts/nanda-search" "$bin_dir/nanda-search"
ln -sfn "$runtime_skill_dir/scripts/nanda-encode" "$bin_dir/nanda-encode"
ln -sfn "$runtime_skill_dir/scripts/nanda-decode" "$bin_dir/nanda-decode"
ln -sfn "$runtime_skill_dir/scripts/nanda-decode-eval" "$bin_dir/nanda-decode-eval"
ln -sfn "$runtime_skill_dir/scripts/nanda-pattern-store" "$bin_dir/nanda-pattern-store"
ln -sfn "$runtime_skill_dir/scripts/nanda-pattern-capacity" "$bin_dir/nanda-pattern-capacity"
ln -sfn "$runtime_skill_dir/scripts/nanda-pattern-eval" "$bin_dir/nanda-pattern-eval"
ln -sfn "$runtime_skill_dir/scripts/nanda-llmwave" "$bin_dir/nanda-llmwave"
ln -sfn "$runtime_skill_dir/scripts/nanda-focus" "$bin_dir/nanda-focus"
ln -sfn "$runtime_skill_dir/scripts/nanda-proof" "$bin_dir/nanda-proof"
ln -sfn "$runtime_skill_dir/scripts/nanda-probe" "$bin_dir/nanda-probe"
ln -sfn "$runtime_skill_dir/scripts/nanda-dataset-doctor" "$bin_dir/nanda-dataset-doctor"
ln -sfn "$runtime_skill_dir/scripts/nanda-aliases" "$bin_dir/nanda-aliases"
ln -sfn "$runtime_skill_dir/scripts/nanda-budget" "$bin_dir/nanda-budget"
ln -sfn "$runtime_skill_dir/scripts/nanda-pack6m" "$bin_dir/nanda-pack6m"
ln -sfn "$runtime_skill_dir/scripts/nanda-bench6m" "$bin_dir/nanda-bench6m"
ln -sfn "$runtime_skill_dir/scripts/nanda-serve" "$bin_dir/nanda-serve"
ln -sfn "$runtime_skill_dir/scripts/nanda-dogfood" "$bin_dir/nanda-dogfood"
ln -sfn "$runtime_skill_dir/scripts/nanda-report" "$bin_dir/nanda-report"
ln -sfn "$runtime_skill_dir/scripts/nanda-split" "$bin_dir/nanda-split"
ln -sfn "$runtime_skill_dir/scripts/nanda-split-md" "$bin_dir/nanda-split-md"
ln -sfn "$runtime_skill_dir/scripts/nanda-map" "$bin_dir/nanda-map"
ln -sfn "$runtime_skill_dir/scripts/nanda-map-code" "$bin_dir/nanda-map-code"
ln -sfn "$runtime_skill_dir/scripts/nanda-hgate" "$bin_dir/nanda-hgate"

echo "Installed skill: $runtime_skill_dir"
echo "Installed CLI:   $bin_dir/nanda"
echo "Installed CLI:   $bin_dir/nanda-check"
echo "Installed gate:  $bin_dir/nanda-gate"
echo "Installed init:  $bin_dir/nanda-init-task"
echo "Installed pack:  $bin_dir/nanda-pack-from-md"
echo "Installed md:    $bin_dir/nanda-init-md"
echo "Installed mdgate:$bin_dir/nanda-gate-md"
echo "Installed self:  $bin_dir/nanda-self-check"
echo "Installed comb:  $bin_dir/nanda-comb"
echo "Installed doctor:$bin_dir/nanda-doctor"
echo "Installed extract:$bin_dir/nanda-extract"
echo "Installed eval:  $bin_dir/nanda-eval"
echo "Installed waw:   $bin_dir/nanda-waw"
echo "Installed feedback:$bin_dir/nanda-feedback"
echo "Installed index: $bin_dir/nanda-index"
echo "Installed search:$bin_dir/nanda-search"
echo "Installed encode:$bin_dir/nanda-encode"
echo "Installed decode:$bin_dir/nanda-decode"
echo "Installed decode-eval:$bin_dir/nanda-decode-eval"
echo "Installed pattern-store:$bin_dir/nanda-pattern-store"
echo "Installed pattern-capacity:$bin_dir/nanda-pattern-capacity"
echo "Installed pattern-eval:$bin_dir/nanda-pattern-eval"
echo "Installed llmwave:$bin_dir/nanda-llmwave"
echo "Installed focus: $bin_dir/nanda-focus"
echo "Installed proof: $bin_dir/nanda-proof"
echo "Installed probe: $bin_dir/nanda-probe"
echo "Installed dataset-doctor:$bin_dir/nanda-dataset-doctor"
echo "Installed aliases:$bin_dir/nanda-aliases"
echo "Installed budget:$bin_dir/nanda-budget"
echo "Installed pack6m:$bin_dir/nanda-pack6m"
echo "Installed bench6m:$bin_dir/nanda-bench6m"
echo "Installed serve: $bin_dir/nanda-serve"
echo "Installed dog:   $bin_dir/nanda-dogfood"
echo "Installed report:$bin_dir/nanda-report"
echo "Installed split: $bin_dir/nanda-split"
echo "Installed split: $bin_dir/nanda-split-md"
echo "Installed map:   $bin_dir/nanda-map"
echo "Installed code-map:$bin_dir/nanda-map-code"
echo "Installed hgate: $bin_dir/nanda-hgate"
echo "Run: nanda-check --help"
